### ISSUE TITLE
"./casf run" will crash with '{date} no such file or directory'

### ISSUE THREAD

**Issue by benjiae** [catalyys/cas-farewell#9]
Hi, i've been wanting to run this and when i try to run it i find this

```
$  ./casf run
2023/01/30 22:46:34 no such file or directory 
```

This has happened on gentoo and arch (which i'm currently running).
I installed it cloning the repo and running "go build"

**Comment by catalyys** [comment]
Hi, you need a savefile in slot 3.
You can try `./casf run -save 0` if you want to use the first saveslot.
Otherwise you can also just start a run in your third saveslot and then start the with `./casf run`.

If that doesn't work you can try to locate the savepath from celeste.
Do you use the steam version?

**Comment by benjiae** [comment]
Thanks! i didn't know it used the 3rd saveslot
and i use the itch.io version (also ~/.local/share/Celeste)
